# Generated by Django 4.0.4 on 2022-04-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('body', models.BinaryField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_current', to='sessions.session')),
            ],
        ),
    ]
