# Generated by Django 4.0.4 on 2022-04-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRecognizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
