# Generated by Django 4.0.4 on 2022-04-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRecognizer', '0003_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Models',
        ),
    ]
