# Generated by Django 4.0.4 on 2022-04-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRecognizer', '0004_rename_model_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
